### ISSUE TITLE
Quick Start Sample doesn't work 

### ISSUE THREAD

**Issue by sacquatella** [theopenconversationkit/tock-react-kit#160]
It seems that the Quick Start sample provided in readme doesn't work.
He works well with tock-react-kit  22.3.0 but not with upper versions. 
 
Changes have an impact on https://doc.tock.ai/fr/ web site, the bot included with last tock-react-kit  stop working.

**Comment by Fabilin** [comment]
Hello, yes it seems that the instructions in the readme are now outdated. You now need React 17 or higher, and Emotion 11 or higher, so the script tags from the Quick Start HTML need to be updated.

**Comment by Fabilin** [comment]
Alright, so I've got a few thoughts here. I believe this issue highlights the fact that HTML script tags are not a good replacement for a dependency management system - they will not tell you when you need to bump a version number, nor will they warn you when two of your dependencies are conflicting. On top of this, other libraries are starting to phase out UMD exports, which makes it more difficult to use them as external dependencies in a browser environment (relevant case for us is the new [React 17 JSX runtime](https://github.com/facebook/react/issues/20923), which will become necessary if we want to use the new JSX transform).
Finally, having multiple script tags means having multiple downloads before running the script. While in theory this could be faster due to browsers caching the React and Emotion scripts between websites, in practice most modern websites bundle these libraries themselves and so the browser ends up downloading it all specifically for bot pages - while if we bundled it as well, we could tree shake it to reduce the final footprint.

My proposal would therefore be, that we distribute a `tock-react-kit-standalone` file that can be used directly within web pages without declaring external dependencies. The immediate benefit (on top of all the above) would be that the Quick Start would be even shorter and easier to maintain long term. The downside would be that this standalone script would not be compatible with other React widgets, and so the websites that already use React would have to import the `tock-react-kit` as an NPM module.

Does this appear reasonable to you @correi-f @rkuffer @sacquatella?

**Comment by rkuffer** [comment]
I have no objection to the creation of a new stand-alone version, but this should not exempt us from thinking about updating the readme of the current version when a dependency version is upgraded.
By the way, it still hasn't been fixed on the repo and the Tock demo site is still in error.

**Comment by Fabilin** [comment]
You are right, the readme should have been updated within #118, it was an oversight that was unfortunately caught by none of the contributors who reviewed the changes during the time the PR was open.
I can open a pull request today with the changes I proposed and a documentation update, if we can get reviews done quickly I believe we can merge it this week. The demo site should come right after, although I do not know if I will have the time to deal with it myself.
